(ns fb.lol
  (:use [jayq.core :only [$ inner delegate]]
        [jayq.util :only [clj->js]]
        [fb.sql :only [do-proj do-buddies do-row row-seq do-cost do-costs do-buddy do-settings
                       update-settings up-cost up-buddy
                       db-init add-cost add-buddy add-proj
                       nuke-db rm-proj rm-cost rm-buddy]]
        [fb.vis :only [set-title-project set-rect-back set-tot-rect-back money buddy]]
        [fb.misc :only [mk-settings add-data trim num]]
        [fb.pages :only [add-page-init! load-template swap-page trigger-new-page]]
        [fb.init :only [add-init! do-inits]]
        ; FIXME get :use to import everything.
        ))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;; init
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


(add-init! #(trigger-new-page "projects" nil) :last)
(do-inits)


; DEBUG:
; #(js/console.log %)
;
; TODO:
; - now:
;   - important:
;     - add phonegap for contacts.
;     - try zepto instead of jquery, benchmark.
;     - remove row-seq and extend js row obj instead.
;     - cljs advanced optimisation for compiling
;     - update jqtouch from github.
;
;   - misc:
;     - add back/forward browser integration?
;     - better sql (remove costs.total, add views and shit?)
;     - logs on sql error
;
;   - UI: better compass themes: 
;     - simple white with blue borders.
;     - fetch Canvas colors from theme.css
;     - add phone.css to be generated by theme/compass.
;
;   - Tests:
;     - test with empty db, empty entries
;     - try going back until back stack is empty.
; 
; - v2:
;   - multiple people add finance to same projects (node.js)
;
; - add ryanday.net [trend.]builtwith.com blog.jqtouch rss
